### ISSUE TITLE
pcs:login {bduss} {stoken} Alfred里输入没有反应？

### ISSUE THREAD

**Issue by wisinfun** [zacksleo/pcs-alfred-workflow#1]
![image](https://user-images.githubusercontent.com/41355260/113711983-29ba0c00-9718-11eb-962d-ae10f5a9e01b.png)
加了{}也没反应

找到原因了，我的python目录不一致
![image](https://user-images.githubusercontent.com/41355260/113729796-ec5e7a00-9729-11eb-9278-4beac78342e0.png)

**Comment by zacksleo** [comment]
你的目录是多少？
